<?php

namespace SL\ThesaurusBundle\Repository;

/**
 * SynonymRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynonymRepository extends \Doctrine\ORM\EntityRepository
{

    // returns all the synonyms of one word
    // INPUT : id of the word
    function findAllSynonymsByWord ($idWord) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT W.name
                 FROM SLThesaurusBundle:Word W , SLThesaurusBundle:Synonym S
                 WHERE (S.idWord2=W.id AND S.idWord1 = :word)
                 OR (S.idWord1=W.id AND S.idWord2 = :word)
                 ORDER BY W.name'
            )
            ->setParameter("word", $idWord)
            ->getResult();
    }
}
